[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["@netlify/plugin-nextjs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    name = "Contact Form"
    fields = { name = "string", email = "email", message = "text" }

[[forms.contact.notifications]]
  email = "vishvaasgv@gmail.com"  # Your email address 